Fixing NullReference Exception and not updating nodes on demo site diagram
Blazor-Diagrams/Blazor.Diagrams pull request #364
Opened 2023-10-16 10:14 UTC by K0369

Fixing a null pointer exception on the demo site diagram, that happened when a link was drawn and released on anything else then a portmodel. Fixes #361.

Fixing the value of the nodes not updating, when the target of a link has changed, because the condition 
`oldTarget == null` being never valid.

2023-10-22 09:09 UTC, zHaytam commented
Hello, thank you for the PR ! here are my remarks:

It looks like your PR contains some of my old changes, maybe you need to rebase develop into your branch to only have your changes?

I will also leave some comments in specific lines as well

Thank you again

2023-10-22 09:13 UTC, zHaytam requested changes

2023-10-22 09:13 UTC, zHaytam commented on site/Site/Components/Landing/LandingShowcaseDiagram.razor.cs
> +        if (link.IsAttached && newTarget is not null)
1. `oldTarget` and `newTarget` aren't nullable anymore, which means:
2. In order to check for a "first attach": `if (oldTarget is PositionAnchor && link.IsAttached)`

2023-10-22 09:13 UTC, zHaytam commented on site/Site/Components/Landing/LandingShowcaseDiagram.razor.cs
> +        if (link.Target != null && link.Target.Model is PortModel portModel) portModel.Parent.Refresh();
Same as previous comment, `Target` cannot be null anymore.  
Just check if `Target` is a `SinglePortAnchor`, then get the port from the casted anchor.

2023-10-22 12:23 UTC, K0369 commented on site/Site/Components/Landing/LandingShowcaseDiagram.razor.cs
> +        if (link.IsAttached && newTarget is not null)
I guess the "first attach" comment led to a misunterstanding. 


I think we had a small misunderstanding here with the "first attach". Your intention was that this check (and therefore the refresh) is only done if this is the "first time this link attaches", correct?

2023-10-22 14:33 UTC, zHaytam commented on site/Site/Components/Landing/LandingShowcaseDiagram.razor.cs
> +        if (link.IsAttached && newTarget is not null)
Correct! Sorry if the code is too ugly for it to show... I kind of did this whole website on a little rush

2023-10-23 12:17 UTC, zHaytam approved these changes

2023-10-23 12:18 UTC, merged