Adding ScaleFactor Zoom Option to allow customized zoom rate.
Blazor-Diagrams/Blazor.Diagrams pull request #87
Opened 2021-04-08 18:09 UTC by joezearing

2021-04-08 21:39 UTC, zHaytam requested changes

2021-04-08 21:44 UTC, joezearing commented on src/Blazor.Diagrams.Core/DiagramOptions.cs
> +        public double ScaleFactor { get; set; } = 1.2;
Yes, my mistake, was testing 1.2 out and forgot to change back...

2021-04-09 00:14 UTC, zHaytam commented on src/Blazor.Diagrams.Core/DiagramOptions.cs
> +        public double ScaleFactor { get; set; } = 1.2;
Can you please update it so I can merge the PR?

2021-04-09 17:13 UTC, joezearing commented on src/Blazor.Diagrams.Core/DiagramOptions.cs
> +        public double ScaleFactor { get; set; } = 1.2;
Updated. Thanks!

2021-04-09 22:56 UTC, zHaytam approved these changes

2021-04-12 10:11 UTC, merged

2021-04-12 10:11 UTC, zHaytam commented
Thanks a lot for the MR!